import sys
import os
from PIL import Image
import numpy as np
import re
import cv2
import shutil

def extract_surprise(input_video_path, output_path, verbose=False): #note: input video path is not used in this script, but the wrapper class expects two arguments

    output_dir = os.path.dirname(output_path)           #directory for folders and final mp4 (change as needed)
    input_dir = os.path.join(os.path.dirname(output_dir), 'frequency/heat_outputs')          #replace with location of Jimmy's heat_outputs folder

    if not os.path.exists(input_dir):
        print(f"ERROR: Could not find input heatmap directory at {input_dir}")


    out_dir = f"{output_dir}_surprise"     #directory used for surprise maps later DO NOT CHANGE

    def mono(dir):
        os.makedirs(dir, exist_ok=True)
        for file in sorted(os.listdir(input_dir)):
            file_path  = os.path.join(input_dir, file)
            i = re.findall(r'\d+', file)
            file_num = [int(x) for x in i]

            if file_path.endswith(".mp4") and verbose:
                print("MP4 FOUND, SKIPPING")    #skips the heatmap video generated by jimmy's code

            elif file_num[0] % 30 == 0:         #grabs 1 of each of the heatmaps
                #print("IMAGE FOUND")
                #print(file_num[0])
                input = Image.open(file_path)

                output = input.convert('L')     #converts to mono and renames
                x = file_num[0] // 30
                image_path = f"{x:04d}.png"
                output.save(os.path.join(dir, image_path))
        average_test()


    def average_test():
        try:
            shutil.rmtree(out_dir)
        except:
            pass
        os.makedirs(out_dir, exist_ok=True)
        #os.makedirs('np_test', exist_ok=True)
        current_file = 0
        prev_average_array = float(0)
        output_num = 0
        brightness = 0
        for file in sorted(os.listdir(output_dir)):

            if not file.endswith('.png'):
                continue


            file_path  = os.path.join(output_dir, file)
            current_image = Image.open(file_path)
            current_array = np.array(current_image, dtype=np.float32)
            #current_array = np.array(current_array, dtype=np.uint8)
            #test_image = Image.fromarray(current_array, 'L')
            #test_image.save(os.path.join('np_test', file))




            if current_file == 0:
                average_array = current_array
                brightness = current_array.max()

            else:
                prev_average_array = prev_average_array / float(current_file)
                average_array = (prev_average_array * 0.5 + current_array * 0.5)
                current_array_row, current_array_col = surprise_location(current_array)
                prev_array_row, prev_array_col = surprise_location(prev_average_array)

                #gets the distance of max brightness locations of current and previous average array
                row_dif = abs(current_array_row - prev_array_row)
                col_dif = abs(current_array_col - prev_array_col)


                #DEBUG: prints max brightness in current or average np array
                #print("Current Array Max Brightness: ", current_array.max())
                #print("Previous Arrays Max Brightness: ", prev_average_array.max())


                #DISTANCE TOLERANCE
                #After testing I determined that a verticle distance of 4 pixels on both sides
                #and a horizontal distance of 6 pixels on both sides created the best results
                if ((row_dif >= 32 or row_dif <=3) and (col_dif >= 66 or col_dif <= 5)):
                    if (current_array.max() >= brightness + 100 and verbose):
                        print("SURPRISE HAS OCCURD AT ", current_file, " SECOND(S) DUE TO VOLUME SPIKE")
                    else:
                        average_array = average_array * 0

                else:

                    verbose and print("SURPRISE HAS OCCURD AT ", current_file, " SECOND(S)")

                    #DEBUG: gives exact location of surprising stimulus
                    #print("Current Column: ", current_array_col)
                    #print("Previous Column: ", prev_array_col)
                    #print("Current Row: ", current_array_row)
                    #print("Previous Row: ", prev_array_row)

                brightness = current_array.max()

            average_array[average_array < (average_array.max() - average_array.max() / 10)] = 0
            average_array = np.clip(average_array, 0, 255)
            average_array = np.array(average_array, dtype=np.uint8)

            average_image = Image.fromarray(average_array, 'L')
            for i in range(30):
                x = output_num
                file = f"{x:04d}.png"
                average_image.save(os.path.join(out_dir, file))
                output_num += 1

            prev_average_array += current_array
            current_file += 1
        create_video()



    def surprise_location(image):   #returns the x,y coordinates of max value in np array
        max_brightness_index = image.argmax()
        return(max_brightness_index // 72, max_brightness_index % 72)


    def create_video():     #similar to Jimmy's video creater, but more simple
        #video_out = f"{out_dir}_map.mp4"
        video = cv2.VideoWriter(output_path, cv2.VideoWriter_fourcc(*'mp4v'), 30, (72, 36), isColor=False)
        for file in sorted(os.listdir(out_dir)):
            video.write(cv2.imread(os.path.join(out_dir, file), cv2.IMREAD_GRAYSCALE))  #supposedly the images have 3 channels even though they're greyscale, IMREAD_GREYSCALE fixes that

        video.release()
        cv2.destroyAllWindows()


    mono(output_dir)
